version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "6969:5050"
    environment:
      - SWAPI_BASE_URL=https://swapi.dev/api
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
